INSERT INTO Comments (userId, postId, content) VALUES
(2, 1, 'I saw a Donkey Kong cab on eBay last week! Might still be available.'),
(3, 1, 'Check with local arcades, some sell old machines when they upgrade.'),
(4, 2, 'How much are you asking for the Pac-Man cab? I’m interested!'),
(5, 2, 'Wish I was closer to Chicago! That’s a great find.'),
(6, 3, 'Try replacing the CRT with a new chassis. Worked for my SF2 cab.'),
(7, 3, 'There’s a guy on Arcade Forums who fixes those monitors.'),
(8, 4, 'Medieval Madness is super rare! Good luck finding one.'),
(9, 4, 'Check Pinside marketplace, they have rare pinball listings.'),
(10, 5, 'I have an extra SNES with controllers, DM me if interested!'),
(1, 5, 'You should check local retro gaming shops, they sometimes have consoles.'),
(2, 6, 'There’s an auction next month in Texas selling old arcade cabinets!'),
(3, 6, 'Warehouse sales are great, but you need a truck to haul stuff.'),
(4, 7, 'For Galaga parts, check Arcade Parts and Repair, they have good stuff.'),
(5, 7, 'Post pics of your restoration! Always love seeing arcade rebuilds.'),
(6, 8, 'I have a TMNT cab but looking for NBA Jam instead. Let me know.'),
(7, 8, 'That’s a great trade! Hope you find a good deal.'),
(8, 9, 'Addams Family pinball is amazing! I wish I could afford one.'),
(9, 9, 'Where are you located? I might be interested in one of these.'),
(10, 10, 'Try Barcade locations, they have original arcade cabinets!'),
(1, 10, 'There’s a place in LA with tons of classics, I’ll find the name.');
